[package]
authors = ["pegasis"]
name = "tiny-nmea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = { version = "0.7.5", default-features = false }